exports.constants = {
  STATUS_OK: 200,
  STATUS_CREATED: 201,
  STATUS_BAD_REQUEST: 400,
  STATUS_UNAUTHORIZED: 401,
  STATUS_FORBIDDEN: 403,
  STATUS_NOT_FOUND: 404,
  STATUS_INTERNAL_SERVER_ERROR: 500,
  STATUS_NOT_IMPLEMENTED: 501,
  STATUS_SERVICE_UNAVAILABLE: 503,
  STATUS_GATEWAY_TIMEOUT: 504,
  STATUS_NO_CONTENT: 204,
};
